**" Importing the libraries"**

In [ ]:
!pip install pandas_profiling

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [ ]:
!pip install pandas

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [ ]:
!pip install matplotlib

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import pandas_profiling as pl

In [ ]:
from google .colab import files
import io
uploaded=files.upload()

Saving data (1).csv to data (1).csv


In [ ]:
data=pd.read_csv(io.BytesIO(uploaded['data (1).csv']))
data.head()

date      price  bedrooms  bathrooms  sqft_living  sqft_lot  \
0  2014-05-02 00:00:00   313000.0       3.0       1.50         1340      7912   
1  2014-05-02 00:00:00  2384000.0       5.0       2.50         3650      9050   
2  2014-05-02 00:00:00   342000.0       3.0       2.00         1930     11947   
3  2014-05-02 00:00:00   420000.0       3.0       2.25         2000      8030   
4  2014-05-02 00:00:00   550000.0       4.0       2.50         1940     10500   

   floors  waterfront  view  condition  sqft_above  sqft_basement  yr_built  \
0     1.5           0     0          3        1340              0      1955   
1     2.0           0     4          5        3370            280      1921   
2     1.0           0     0          4        1930              0      1966   
3     1.0           0     0          4        1000           1000      1963   
4     1.0           0     0          4        1140            800      1976   

   yr_renovated                    street       city  statezip country  
0          2005      18810 Densmore Ave N  Shoreline  WA 98133     USA  
1             0           709 W Blaine St    Seattle  WA 98119     USA  
2             0  26206-26214 143rd Ave SE       Kent  WA 98042     USA  
3             0           857 170th Pl NE   Bellevue  WA 98008     USA  
4          1992         9105 170th Ave NE    Redmond  WA 98052     USA

In [ ]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

In [ ]:
dataset = pd.read_csv('data (1).csv')

In [ ]:
df=pd.DataFrame(data)

In [ ]:
df

date         price  bedrooms  bathrooms  sqft_living  \
0     2014-05-02 00:00:00  3.130000e+05       3.0       1.50         1340   
1     2014-05-02 00:00:00  2.384000e+06       5.0       2.50         3650   
2     2014-05-02 00:00:00  3.420000e+05       3.0       2.00         1930   
3     2014-05-02 00:00:00  4.200000e+05       3.0       2.25         2000   
4     2014-05-02 00:00:00  5.500000e+05       4.0       2.50         1940   
...                   ...           ...       ...        ...          ...   
4595  2014-07-09 00:00:00  3.081667e+05       3.0       1.75         1510   
4596  2014-07-09 00:00:00  5.343333e+05       3.0       2.50         1460   
4597  2014-07-09 00:00:00  4.169042e+05       3.0       2.50         3010   
4598  2014-07-10 00:00:00  2.034000e+05       4.0       2.00         2090   
4599  2014-07-10 00:00:00  2.206000e+05       3.0       2.50         1490   

      sqft_lot  floors  waterfront  view  condition  sqft_above  \
0         7912     1.5           0     0          3        1340   
1         9050     2.0           0     4          5        3370   
2        11947     1.0           0     0          4        1930   
3         8030     1.0           0     0          4        1000   
4        10500     1.0           0     0          4        1140   
...        ...     ...         ...   ...        ...         ...   
4595      6360     1.0           0     0          4        1510   
4596      7573     2.0           0     0          3        1460   
4597      7014     2.0           0     0          3        3010   
4598      6630     1.0           0     0          3        1070   
4599      8102     2.0           0     0          4        1490   

      sqft_basement  yr_built  yr_renovated                    street  \
0                 0      1955          2005      18810 Densmore Ave N   
1               280      1921             0           709 W Blaine St   
2                 0      1966             0  26206-26214 143rd Ave SE   
3              1000      1963             0           857 170th Pl NE   
4               800      1976          1992         9105 170th Ave NE   
...             ...       ...           ...                       ...   
4595              0      1954          1979            501 N 143rd St   
4596              0      1983          2009          14855 SE 10th Pl   
4597              0      2009             0          759 Ilwaco Pl NE   
4598           1020      1974             0         5148 S Creston St   
4599              0      1990             0         18717 SE 258th St   

           city  statezip country  
0     Shoreline  WA 98133     USA  
1       Seattle  WA 98119     USA  
2          Kent  WA 98042     USA  
3      Bellevue  WA 98008     USA  
4       Redmond  WA 98052     USA  
...         ...       ...     ...  
4595    Seattle  WA 98133     USA  
4596   Bellevue  WA 98007     USA  
4597     Renton  WA 98059     USA  
4598    Seattle  WA 98178     USA  
4599  Covington  WA 98042     USA  

[4600 rows x 18 columns]

Extracting Independent and dependent Variable

In [ ]:
y = data.iloc[: , 1:2].values
x = data.iloc[: ,[2,3,4,5,6,9,10,12]].values
print(x)

[[3.000e+00 1.500e+00 1.340e+03 ... 3.000e+00 1.340e+03 1.955e+03]
 [5.000e+00 2.500e+00 3.650e+03 ... 5.000e+00 3.370e+03 1.921e+03]
 [3.000e+00 2.000e+00 1.930e+03 ... 4.000e+00 1.930e+03 1.966e+03]
 ...
 [3.000e+00 2.500e+00 3.010e+03 ... 3.000e+00 3.010e+03 2.009e+03]
 [4.000e+00 2.000e+00 2.090e+03 ... 3.000e+00 1.070e+03 1.974e+03]
 [3.000e+00 2.500e+00 1.490e+03 ... 4.000e+00 1.490e+03 1.990e+03]]


Splitting the dataset into training and test set.

In [ ]:
from sklearn.model_selection import train_test_split 
x_train, x_test, y_train, y_test= train_test_split(x, y, test_size= 0.33, random_state=0)

Fitting the MLR model to the training set:

In [ ]:
regressor= LinearRegression()  
regressor.fit(x_train, y_train) 

LinearRegression()

Predicting the Test set result

In [ ]:
y_pred= regressor.predict(x_test)

In [ ]:
df = pd.DataFrame({'Real Values':[y_test], 'Predicted Values':[y_pred]})
print(df)

                                         Real Values  \
0  [[289000.0], [429900.0], [129000.0], [600000.0...   

                                    Predicted Values  
0  [[505275.63392514735], [633407.7507129395], [2...  


trying to predict new values

In [ ]:
pred= regressor.predict([[66051.52,182645.56,118148.2,546,6467,1,555,2000]]).reshape(-1, 1)
print("I predict for you : ", pred[0])

I predict for you :  [5.57828416e+09]
